server:
  port: 8082
spring:
  application:
    name: recipe-service
  config:
    import: optional:configserver:https://crumbs-config-server.herokuapp.com
  cloud:
    config:
      uri: https://crumbs-config-server.herokuapp.com
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
grpc:
  client:
    recipe-service-grpc:
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
      address: discovery:///system-events
