server:
  port: 8082
spring:
  application:
    name: recipe-service
  config:
    import: optional:configserver:https://crumbs-config-server.herokuapp.com
  cloud:
    config:
      uri: https://crumbs-config-server.herokuapp.com
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true
eureka:
  instance:
    preferIpAddress: true
grpc:
  server:
    port: 9092
