server:
  port: 8090

spring:
  application:
    name: gateway-service

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 6000
  ignored-services: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
      url: http://localhost:8081
    review-service:
      path: /review-service/**
      serviceId: review-service
      url: http://localhost:8083
    notification-service:
      path: /notification-service/**
      serviceId: notification-service
      url: http://localhost:8084
    recipe-service:
      path: /recipe-service/**
      serviceId: recipe-service
      url: http://localhost:8082

ribbon:
  eureka:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: https://crumbs-discovery-server.herokuapp.com/eureka/
