server:
  port: 8090

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:https://crumbs-config-server.herokuapp.com
  cloud:
    config:
      uri: https://crumbs-config-server.herokuapp.com

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 6000
  ignored-services: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
      url: https://crumbs-user-service.herokuapp.com/
    review-service:
      path: /review-service/**
      serviceId: review-service
      url: https://crumbs-review-service.herokuapp.com/
    notification-service:
      path: /notification-service/**
      serviceId: notification-service
      url: https://crumbs-notification-service.herokuapp.com/
    recipe-service:
      path: /recipe-service/**
      serviceId: recipe-service
      url: https://crumbs-recipe-service.herokuapp.com/

ribbon:
  eureka:
    enabled: true

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
