server:
  port: 8090

spring:
  application:
    name: gateway-service

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
      stripPrefix: true
      url: http://localhost:8081
