server:
  port: 8087
spring:
  application:
    name: system-events
  config:
    import: optional:configserver:https://crumbs-config-server.herokuapp.com
  cloud:
    config:
      uri: https://crumbs-config-server.herokuapp.com
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
grpc:
  server:
    port: 0   # Random port number