server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://ec2-54-155-226-153.eu-west-1.compute.amazonaws.com:5432/d75d4ailid467f
    username: tykptcfbkuiaxb
    password: bf9acf118d9ed1720f79bd30dde99b131dfd562dea86e934a93db201b833e1bc
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
