server:
  port: 8761
spring:
  application:
    name: eureka
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 2000
  instance:
    prefer-ip-address: true
